spring:
  application:
    name: analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.PostgresSQLDialect
kafka:
  config:
  bootstrap-servers: localhost:9092
  hub-consumer:
        group-id: hub-analyzer-group
        client-id: hub-consumer-1
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.avro.HubEventDeserializer
        attempt-timeout: 1000

  snapshot-consumer:
        group-id: snapshot-analyzer-group
        client-id: snapshot-consumer-1
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.avro.SensorSnapshotDeserializer
        attempt-timeout: 1000

  hub-events-topic: telemetry.hubs.v1
  sensor-snapshots-topic: telemetry.snapshots.v1

grpc:
  client.hub-router:
    address: 'static://localhost:59091'
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext